FROM node:10-alpine
RUN npm install -g create-react-app \
                   create-react-native-app \
                   react-native-cli
RUN mkdir /usr/app
WORKDIR /usr/app
ADD . /usr/app

WORKDIR /usr/app/myapp
CMD [ "yarn", "start" ]